version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # taken from host env
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 15
    networks:
      - myapp-network

  backend:
    image: my-backend:latest
    container_name: backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_PASSWORD: ${POSTGRES_PASSWORD}  # taken from host env
    ports:
      - "8000:8000"
    networks:
      - myapp-network

  frontend:
    image: my-frontend:latest
    container_name: frontend
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:80"
    networks:
      - myapp-network

networks:
  myapp-network:
    driver: bridge
