name: Backend Tests
run-name: ${{ github.actor }} is running Backend Tests at ${{ github.event.head_commit.timestamp }}
on:
  push:
    paths:
      - 'backend/**'

jobs:
  test-backend:
    name: Test backend job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: echo "💡 The Python setup is complete."

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - run: echo "💡 The pip cache is set up."

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "💡 The dependencies are installed."

      - name: Run tests
        run: |
            pytest -v
            echo "💡 The tests are finished."


