name: Docker Deploy
run-name: ${{ github.actor }} is running Docker Deploy at ${{ github.event.head_commit.timestamp }}
on: push

jobs:
    docker-verify:
        name: Docker verify job
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v5
    
          - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    
          - name: Build backend image
            run: |
                docker build -f Dockerfile-backend -t my-backend:latest .
                echo "💡 Backend image built."
    
          - name: Build frontend image
            run: |
                docker build -f Dockerfile-frontend -t my-frontend:latest .
                echo "💡 Frontend image built."
    
          - name: Create Docker network
            run: |
                docker network create myapp-network
                echo "💡 Docker network created."

          - name: Run backend
            run: |
                docker run -d --name backend --network myapp-network -p 8000:8000 my-backend:latest
                echo "💡 Backend running." 
    
          - name: Run frontend
            run: |
                docker run -d --name frontend --network myapp-network -p 5173:80 my-frontend:latest
                echo "💡 Frontend running."
    
          - name: Wait for backend to start
            run: sleep 5
    
          - name: Verify backend
            run: |
                curl --fail http://localhost:8000/ping
                echo "💡 Backend verified."
    
          - name: Verify frontend
            run: | 
                pytest -m e2e
                echo "💡 Frontend verified."